name: petverse
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # 🔥 Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.15.0

  # ✅ ADD THIS (for date/time formatting)
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # 🔶 App icon generator
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_symbol.png"
  adaptive_icon_background: "#0D0D0D"
  adaptive_icon_foreground: "assets/images/app_symbol.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_symbol.png
    - assets/images/app_logo.png
    - assets/images/onboarding_page1.png
    - assets/images/onboarding_page2.png
    - assets/images/onboarding_page3.png
    - assets/images/onboarding_page4.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600