// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDG3RATlVYslW0w69qrfJ-jzajUtAPQlGA',
    appId: '1:142409290851:web:798d257b676c539927d456',
    messagingSenderId: '142409290851',
    projectId: 'petverse-d9ac7',
    authDomain: 'petverse-d9ac7.firebaseapp.com',
    databaseURL: 'https://petverse-d9ac7-default-rtdb.firebaseio.com',
    storageBucket: 'petverse-d9ac7.firebasestorage.app',
    measurementId: 'G-TGZLNYMFHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRNlTdcHkpUoMVnripd2wuVxMvDwMKMV8',
    appId: '1:142409290851:android:0f60a8d9e5eb45b827d456',
    messagingSenderId: '142409290851',
    projectId: 'petverse-d9ac7',
    databaseURL: 'https://petverse-d9ac7-default-rtdb.firebaseio.com',
    storageBucket: 'petverse-d9ac7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsCeCrYTdpY8jgdbWHMXb-lchBuk19_uc',
    appId: '1:142409290851:ios:e44d60a784edbfb927d456',
    messagingSenderId: '142409290851',
    projectId: 'petverse-d9ac7',
    databaseURL: 'https://petverse-d9ac7-default-rtdb.firebaseio.com',
    storageBucket: 'petverse-d9ac7.firebasestorage.app',
    androidClientId: '142409290851-70c8e8699g0u3k49h53j07q2fu8i3q4j.apps.googleusercontent.com',
    iosClientId: '142409290851-egnklg4d45gjjaqdotpdg65q0in0v8aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.petverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsCeCrYTdpY8jgdbWHMXb-lchBuk19_uc',
    appId: '1:142409290851:ios:e44d60a784edbfb927d456',
    messagingSenderId: '142409290851',
    projectId: 'petverse-d9ac7',
    databaseURL: 'https://petverse-d9ac7-default-rtdb.firebaseio.com',
    storageBucket: 'petverse-d9ac7.firebasestorage.app',
    androidClientId: '142409290851-70c8e8699g0u3k49h53j07q2fu8i3q4j.apps.googleusercontent.com',
    iosClientId: '142409290851-egnklg4d45gjjaqdotpdg65q0in0v8aa.apps.googleusercontent.com',
    iosBundleId: 'com.example.petverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDG3RATlVYslW0w69qrfJ-jzajUtAPQlGA',
    appId: '1:142409290851:web:91ceb2f791f84d0c27d456',
    messagingSenderId: '142409290851',
    projectId: 'petverse-d9ac7',
    authDomain: 'petverse-d9ac7.firebaseapp.com',
    databaseURL: 'https://petverse-d9ac7-default-rtdb.firebaseio.com',
    storageBucket: 'petverse-d9ac7.firebasestorage.app',
    measurementId: 'G-Y4M95LJ9BG',
  );
}
